version: '3.9'
services:
 python1:
  build: ./flask-app-docker
  container_name: p1
  command: flask run --host=0.0.0.0
  ports:
      - "5000:5000"
  volumes:
      - ./flask-app-docker/:/app
  environment:
      PORT: 5000
      FLASK_DEBUG: 1    
           
